import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/globals.module.css'
import {Welcome} from '../stepsreens/Welcome'
import React from 'react'
import { GithubCheck } from '../stepsreens/GithubCheck'

const stepsComponents = {
  0: Welcome,
  1: GithubCheck,
  2: EnterUserName,
  3: ChooseAvatarStep,
  4: EnterPhoneStep,
  5: EnterCodeStep,
};

export type UserData = {
  id: number;
  fullname: string;
  avatarUrl: string;
  isActive: number;
  username: string;
  phone: string;
  token?: string;

};


type MyContextProps = {
  onNextStep: () => void;
  setUserData: React.Dispatch<React.SetStateAction<UserData>>;
  setFieldValue: (field: keyof UserData, value: string) => void;
  step: number;
  userData?: UserData;
 
}

export const MyContext = React.createContext<MyContextProps>({} as MyContextProps);


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Welcome/>
     
    </div>
  )
}
